In [ ]:
import pandas as pd

In [ ]:
#df = pd.read_csv("/content/sample_data/mnist_test.csv")
df = pd.read_excel("/data/Online_Retail.xlsx", engine="openpyxl")

In [ ]:
df.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [1]:
#Create a new column TotalPrice = Quantity × UnitPrice using .apply().
df['TotalPrice']=df.apply(lambda x: x['Quantity']*x['UnitPrice'], axis=1)

NameError: name 'df' is not defined

In [ ]:
df.shape

(541909, 9)

In [ ]:
#Filter all transactions where TotalPrice is above £1000.
df = df[df["TotalPrice"]>1000]

In [ ]:
df.shape

(388, 9)

In [ ]:
#Sort the dataset by TotalPrice in descending order.
df=df.sort_values("TotalPrice", ascending=False)

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom,168469.60
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098.0,United Kingdom,38970.00
15017,537632,AMAZONFEE,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,NaN,United Kingdom,13541.33
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom,11062.06
...,...,...,...,...,...,...,...,...,...
30707,538877,84029E,RED WOOLLY HOTTIE WHITE HEART.,120,2010-12-14 15:29:00,8.47,NaN,United Kingdom,1016.40
536834,581219,DOT,DOTCOM POSTAGE,1,2011-12-08 09:28:00,1008.96,NaN,United Kingdom,1008.96
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,2011-10-27 12:26:00,0.21,12901.0,United Kingdom,1008.00
4850,536809,84950,ASSORTED COLOUR T-LIGHT HOLDER,1824,2010-12-02 16:48:00,0.55,15299.0,United Kingdom,1003.20
58123,541220,22840,ROUND CAKE TIN VINTAGE RED,144,2011-01-14 14:11:00,6.95,14156.0,EIRE,1000.80

In [ ]:
#Group the data by Country and compute total Quantity and TotalPrice.
result  = df.groupby("Country").agg(Total_Quantity=("Quantity", "sum"),
    Total_Price=("TotalPrice", "sum")).reset_index()

In [ ]:
result

           Country  Total_Quantity  Total_Sales
0        Australia            1756      6111.40
1             EIRE            1772     17697.46
2           France             915     11090.90
3        Hong Kong               2      5237.71
4            Japan            4488      9164.40
5      Netherlands            7808     12317.76
6         Portugal               2      2483.96
7        Singapore               5     11757.00
8            Spain            2088      7570.80
9           Sweden             240      1188.00
10  United Kingdom          350042    939850.74

In [ ]:
#Top 5 customers by total spend.
top_customers = (df.groupby("CustomerID")["TotalPrice"].sum().sort_values(ascending=False).head(5))
top_customers

CustomerID
16446.0    168469.60
18102.0    131101.78
17450.0    117558.70
12346.0     77183.60
15749.0     44534.30
Name: TotalPrice, dtype: float64

In [ ]:
#Extract the month from InvoiceDate and count transactions per month
df["Month"] =df["InvoiceDate"].dt.month

In [ ]:
#Filter transactions from the UK with positive Quantity.
transactions_per_month = df.groupby("Month")["InvoiceNo"].value_counts()
transactions_per_month

Month  InvoiceNo
1      540689       4
       540815       3
       541220       3
       540785       2
       540818       2
                   ..
12     581238       1
       581375       1
       581458       1
       581483       1
       581498       1
Name: count, Length: 219, dtype: int64

In [ ]:
#Create a column ValueLabel as 'High' if TotalPrice > 500 else 'Low'.
uk_filter=df[(df["Country"]=="United Kingdom") & (df["Quantity"]>0)]

In [ ]:
uk_filter.shape

(342, 10)

In [ ]:
#Count number of High value transactions by country.
df["ValueLabel"]=df["TotalPrice"].apply(lambda x: "High" if x > 500 else "Low")

In [ ]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Month,ValueLabel
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom,168469.60,12,High
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.60,1,High
222680,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,2011-06-10 15:28:00,649.50,15098.0,United Kingdom,38970.00,6,High
15017,537632,AMAZONFEE,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,NaN,United Kingdom,13541.33,12,High
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom,11062.06,8,High
...,...,...,...,...,...,...,...,...,...,...,...
30707,538877,84029E,RED WOOLLY HOTTIE WHITE HEART.,120,2010-12-14 15:29:00,8.47,NaN,United Kingdom,1016.40,12,High
536834,581219,DOT,DOTCOM POSTAGE,1,2011-12-08 09:28:00,1008.96,NaN,United Kingdom,1008.96,12,High
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,2011-10-27 12:26:00,0.21,12901.0,United Kingdom,1008.00,10,High
4850,536809,84950,ASSORTED COLOUR T-LIGHT HOLDER,1824,2010-12-02 16:48:00,0.55,15299.0,United Kingdom,1003.20,12,High
58123,541220,22840,ROUND CAKE TIN VINTAGE RED,144,2011-01-14 14:11:00,6.95,14156.0,EIRE,1000.80,1,High

In [ ]:
high_counts = (
    df[df["ValueLabel"] == "High"]
      .groupby("Country")["InvoiceNo"]
      .count()
      .reset_index(name="HighCount")    # clean index + rename column
)

print(high_counts)